{
 "title": "PGbouncer",
 "description": "Pgbouncer dashboard for Grafana integrated with Percona PMM as well.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "pgbouncer_up" },
   {
    "name": "database",
    "label": "Database",
    "query": "pgbouncer_databases_database_max_connections"
   },
   { "name": "node", "label": "Node Name", "query": "process_start_time_seconds" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><i><font color=#0091d5><b><center>Statistics</font></center></b></h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 4, "y": 0 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>pgbouncer metrics for </font><font color=#e68a00>$host</font> <font color=#5991A7></font> </font><font color=#e68a00></center></b></font></i></h1><br>"
   },
   "targets": [
    {
     "expr": "avg by (service_name) (pg_up{service_name=~\"$pgbouncer_up\"})"
    }
   ]
  },
  {
   "title": "pgbouncer status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_up{node_ip=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "stat",
   "description": "Maximum connections to Postgres Database",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (database,hostname) (pgbouncer_databases_database_pool_size{database=~\"$database\",node_ip=~\"$host\"})\r"
    }
   ]
  },
  {
   "title": "Reserved Pool",
   "type": "stat",
   "description": "Maximum number of additional connections for this database.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_databases_database_reserve_pool_size{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max DB Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_database_max_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max Client Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_config_max_client_conn{node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max User Conn",
   "type": "stat",
   "description": "Maximum number of allowed connections per-database",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_config_max_user_connections{node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{node_name=\"$node\"} * 1000"
    }
   ]
  },
  {
   "title": "Clients Active",
   "type": "gauge",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Current conn on DB",
   "type": "gauge",
   "description": "Total number of per-database Database connections count",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_databases_database_current_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Used Conn",
   "type": "gauge",
   "description": "Server connections that have been idle for more than `server_check_delay`, so they need `server_check_query` to run on them before they can be used again.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_used_connections{database=\"$database\",node_ip=\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Idle",
   "type": "gauge",
   "description": "Server connections that are unused and immediately usable for client queries.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_idle_connections{database=~\"$database\",node_ip=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Server Tested Conn",
   "type": "gauge",
   "description": "Server connections that are currently running either `server_reset_query` or `server_check_query`.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_server_testing_connections{database=\"$database\",node_ip=\"$host\"})"
    }
   ]
  },
  {
   "title": "Exporter Memory Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{node_name=\"$node\"})"
    }
   ]
  },
  {
   "title": "Exporter CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{node_name=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Clients Active",
   "type": "graph",
   "description": "Server connections that are linked to a client.",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$database\",node_ip=~\"$host\"})",
     "legendFormat": "Active clients"
    }
   ]
  },
  {
   "title": "Client Waiting",
   "type": "graph",
   "description": "How long the first (oldest) client in queue has waited, in seconds",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_maxwait_seconds{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "User: {{user}}"
    }
   ]
  },
  {
   "title": "Total Transaction",
   "type": "stat",
   "description": "Total number of SQL transactions pooled by pgbouncer",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_transactions_total{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "description": "Total number of SQL queries pooled by pgbouncer",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_queries_total{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Transaction Duration",
   "type": "stat",
   "description": "Total number of microseconds spent in a transaction. Includes time spent waiting for an available connection. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_transactions_duration_microseconds_total{database=\"$database\",node_ip=\"$host\"} / 1000000",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Waiting for Server Conn",
   "type": "graph",
   "description": "Client connections have sent queries but have not yet got a server connection",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$database\",node_ip=~\"$host\"}",
     "legendFormat": "user: {{user}}"
    }
   ]
  },
  {
   "title": "Server Conn Logging in process",
   "type": "graph",
   "description": "Server connections currently in logging in process",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_server_login_connections{database=\"$database\",node_ip=\"$host\"}",
     "legendFormat": "User: {{user}}"
    }
   ]
  },
  {
   "title": "Queries Duration",
   "type": "stat",
   "description": "Total number of microseconds spent waiting for a server to return a query response. Includes time spent waiting for an available connection.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_queries_duration_microseconds_total{database=\"$database\",node_ip=\"$host\"} / 1000000",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Waiting",
   "type": "stat",
   "description": "Total number of microseconds spent waiting for an available connection",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_waiting_duration_microseconds_total{database=\"$database\",node_ip=\"$host\"} / 1000000",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes",
   "type": "graph",
   "description": "Total volume in bytes of network traffic sent / received by pgbouncer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_received_bytes_total{database=~\"$database\",node_ip=~\"$host\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$database\",node_ip=~\"$host\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}: Stats sent bytes total"
    }
   ]
  }
 ]
}